// eslint-disable
// ⚠️ DO NOT EDIT ⚠️
// This file is automatically generated, run pnpm run generate to update

/** Internal type. DO NOT USE DIRECTLY. */
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
/** Internal type. DO NOT USE DIRECTLY. */
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
import { gql } from '@apollo/client';
import * as Apollo from '@apollo/client';
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
const defaultOptions = {} as const;
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  Freeform: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type Asset = {
  __typename?: 'Asset';
  contentType?: Maybe<Scalars['String']['output']>;
  contentfulMetadata: ContentfulMetadata;
  description?: Maybe<Scalars['String']['output']>;
  fileName?: Maybe<Scalars['String']['output']>;
  height?: Maybe<Scalars['Int']['output']>;
  size?: Maybe<Scalars['Int']['output']>;
  sys: Sys;
  title?: Maybe<Scalars['String']['output']>;
  url?: Maybe<Scalars['String']['output']>;
  width?: Maybe<Scalars['Int']['output']>;
};


export type AssetUrlArgs = {
  transform?: InputMaybe<ImageTransformOptions>;
};

export type Book = {
  __typename?: 'Book';
  author: Scalars['String']['output'];
  coverUrl?: Maybe<Scalars['String']['output']>;
  fallbackColors?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  readingDate?: Maybe<Scalars['String']['output']>;
  title: Scalars['String']['output'];
  url: Scalars['String']['output'];
};

export enum BookSource {
  Goodreads = 'GOODREADS',
  Literal = 'LITERAL'
}

export enum CollectionType {
  Reading = 'READING'
}

export type ContentfulMetadata = {
  __typename?: 'ContentfulMetadata';
  tags: Array<Maybe<ContentfulTag>>;
};

export type ContentfulTag = {
  __typename?: 'ContentfulTag';
  id?: Maybe<Scalars['String']['output']>;
  name?: Maybe<Scalars['String']['output']>;
};

export type Entry = {
  contentfulMetadata: ContentfulMetadata;
  sys: Sys;
};

export type Flag = {
  __typename?: 'Flag';
  key: Scalars['String']['output'];
  value: Scalars['String']['output'];
};

export type FocalPoint = {
  __typename?: 'FocalPoint';
  x: Scalars['Int']['output'];
  y: Scalars['Int']['output'];
};

export type ImageTransformOptions = {
  backgroundColor?: InputMaybe<Scalars['String']['input']>;
  cornerRadius?: InputMaybe<Scalars['Int']['input']>;
  format?: InputMaybe<Scalars['String']['input']>;
  height?: InputMaybe<Scalars['Int']['input']>;
  quality?: InputMaybe<Scalars['Int']['input']>;
  resizeFocus?: InputMaybe<Scalars['String']['input']>;
  resizeStrategy?: InputMaybe<Scalars['String']['input']>;
  width?: InputMaybe<Scalars['Int']['input']>;
};

export type Location = {
  __typename?: 'Location';
  lat?: Maybe<Scalars['Float']['output']>;
  lon?: Maybe<Scalars['Float']['output']>;
};

export type Photo = {
  __typename?: 'Photo';
  description?: Maybe<Scalars['String']['output']>;
  exif?: Maybe<Scalars['JSON']['output']>;
  focalPoint?: Maybe<FocalPoint>;
  height: Scalars['Int']['output'];
  id: Scalars['String']['output'];
  location?: Maybe<Location>;
  publishedAt?: Maybe<Scalars['String']['output']>;
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  url: Scalars['String']['output'];
  width: Scalars['Int']['output'];
};

export type PhotoSet = {
  __typename?: 'PhotoSet';
  description?: Maybe<Scalars['String']['output']>;
  featuredPhoto: Photo;
  id: Scalars['String']['output'];
  photos?: Maybe<Array<Maybe<Photo>>>;
  slug: Scalars['String']['output'];
  title: Scalars['String']['output'];
  unlisted?: Maybe<Scalars['Boolean']['output']>;
  updatedAt: Scalars['String']['output'];
};

export type Place = {
  __typename?: 'Place';
  location: Location;
  locationType: Scalars['String']['output'];
  name: Scalars['String']['output'];
};

export type Playlist = {
  __typename?: 'Playlist';
  coverUrl: Scalars['String']['output'];
  spotifyUrl: Scalars['String']['output'];
  title: Scalars['String']['output'];
};

export type Post = {
  __typename?: 'Post';
  body: Scalars['Freeform']['output'];
  coverAlt?: Maybe<Scalars['String']['output']>;
  coverUrl?: Maybe<Scalars['String']['output']>;
  metaDescription?: Maybe<Scalars['String']['output']>;
  publishedDate: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  title: Scalars['String']['output'];
};

export type PostWithoutBody = {
  __typename?: 'PostWithoutBody';
  coverUrl?: Maybe<Scalars['String']['output']>;
  metaDescription?: Maybe<Scalars['String']['output']>;
  publishedDate: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  title: Scalars['String']['output'];
};

export type Query = {
  __typename?: 'Query';
  books: Array<Maybe<Book>>;
  lastfmStatus: SpotifyStatus;
  musicStatus: SpotifyStatus;
  photo?: Maybe<Photo>;
  photoSet?: Maybe<PhotoSet>;
  photoSets: Array<Maybe<PhotoSet>>;
  photos: Array<Maybe<Photo>>;
  places: Array<Maybe<Place>>;
  playlists: Array<Maybe<Playlist>>;
  post?: Maybe<Post>;
  posts: Array<Maybe<PostWithoutBody>>;
  siteSettings: SiteSettings;
  spotifyPlaylist: SpotifyPlaylist;
  spotifyStatus: SpotifyStatus;
};


export type QueryBooksArgs = {
  collection?: InputMaybe<CollectionType>;
  limit?: InputMaybe<Scalars['Int']['input']>;
  source?: InputMaybe<BookSource>;
};


export type QueryPhotoArgs = {
  id: Scalars['String']['input'];
};


export type QueryPhotoSetArgs = {
  slug: Scalars['String']['input'];
};


export type QueryPhotoSetsArgs = {
  limit?: InputMaybe<Scalars['Int']['input']>;
};


export type QueryPhotosArgs = {
  limit?: InputMaybe<Scalars['Int']['input']>;
};


export type QueryPlaylistsArgs = {
  limit?: InputMaybe<Scalars['Int']['input']>;
};


export type QueryPostArgs = {
  slug: Scalars['String']['input'];
};


export type QueryPostsArgs = {
  limit?: InputMaybe<Scalars['Int']['input']>;
};


export type QuerySpotifyPlaylistArgs = {
  id: Scalars['String']['input'];
};

export type SiteSettings = {
  __typename?: 'SiteSettings';
  avatar: Asset;
  flags?: Maybe<Array<Maybe<Flag>>>;
  intro: Scalars['String']['output'];
  metaDescription: Scalars['String']['output'];
  siteTitle: Scalars['String']['output'];
};

export type Song = {
  __typename?: 'Song';
  album?: Maybe<Scalars['String']['output']>;
  albumImageUrl?: Maybe<Scalars['String']['output']>;
  artist?: Maybe<Scalars['String']['output']>;
  spotifyUrl?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
};

export type SpotifyPlaylist = {
  __typename?: 'SpotifyPlaylist';
  coverUrl: Scalars['String']['output'];
  followerCount: Scalars['Int']['output'];
  name: Scalars['String']['output'];
  spotifyUrl: Scalars['String']['output'];
  trackCount: Scalars['Int']['output'];
};

export type SpotifyStatus = {
  __typename?: 'SpotifyStatus';
  isPlaying: Scalars['Boolean']['output'];
  playlist?: Maybe<SpotifyPlaylist>;
  song?: Maybe<Song>;
  timestamp?: Maybe<Scalars['String']['output']>;
};

export type Sys = {
  __typename?: 'Sys';
  environmentId: Scalars['String']['output'];
  firstPublishedAt?: Maybe<Scalars['String']['output']>;
  id: Scalars['String']['output'];
  publishedAt?: Maybe<Scalars['String']['output']>;
  publishedVersion?: Maybe<Scalars['Int']['output']>;
  spaceId: Scalars['String']['output'];
};

export type SiteSettingsSharedFragment = { siteTitle: string, metaDescription: string };

export type PageHomeQueryQueryVariables = Exact<{ [key: string]: never; }>;


export type PageHomeQueryQuery = { siteSettings: { intro: string, siteTitle: string, metaDescription: string }, posts: Array<{ publishedDate: string, title: string, slug: string } | null>, books: Array<{ title: string, author: string, url: string, coverUrl: string | null } | null> };

export type MusicStatusQueryQueryVariables = Exact<{ [key: string]: never; }>;


export type MusicStatusQueryQuery = { musicStatus: { timestamp: string | null, isPlaying: boolean, playlist: { name: string, coverUrl: string, spotifyUrl: string } | null, song: { albumImageUrl: string | null, artist: string | null, title: string | null, spotifyUrl: string | null, album: string | null } | null } };

export type PostQueryQueryVariables = Exact<{
  slug: string;
}>;


export type PostQueryQuery = { siteSettings: { siteTitle: string, metaDescription: string, avatar: { url: string | null } }, post: { body: any, coverUrl: string | null, coverAlt: string | null, metaDescription: string | null, publishedDate: string, tags: Array<string | null> | null, title: string } | null };

export type PostsQueryQueryVariables = Exact<{ [key: string]: never; }>;


export type PostsQueryQuery = { posts: Array<{ publishedDate: string, title: string, slug: string, metaDescription: string | null } | null> };

export type PostsFeedQueryQueryVariables = Exact<{ [key: string]: never; }>;


export type PostsFeedQueryQuery = { siteSettings: { siteTitle: string, metaDescription: string }, posts: Array<{ publishedDate: string, title: string, slug: string, metaDescription: string | null } | null> };

export type PostsSlugsQueryQueryVariables = Exact<{ [key: string]: never; }>;


export type PostsSlugsQueryQuery = { posts: Array<{ slug: string } | null> };

export type PlaylistQueryQueryVariables = Exact<{
  id: string;
}>;


export type PlaylistQueryQuery = { spotifyPlaylist: { name: string, coverUrl: string, trackCount: number, followerCount: number, spotifyUrl: string } };

export type PlacesQueryQueryVariables = Exact<{ [key: string]: never; }>;


export type PlacesQueryQuery = { places: Array<{ name: string, locationType: string, location: { lat: number | null, lon: number | null } } | null> };

export type PhotoSetsQueryQueryVariables = Exact<{
  limit?: number | null | undefined;
}>;


export type PhotoSetsQueryQuery = { photoSets: Array<{ id: string, title: string, slug: string, description: string | null, featuredPhoto: { description: string | null, url: string, width: number, height: number, focalPoint: { x: number, y: number } | null } } | null> };

export type PhotoSetQueryQueryVariables = Exact<{
  slug: string;
}>;


export type PhotoSetQueryQuery = { siteSettings: { siteTitle: string, metaDescription: string, avatar: { url: string | null } }, photoSet: { id: string, title: string, slug: string, description: string | null, updatedAt: string, photos: Array<{ id: string, description: string | null, publishedAt: string | null, url: string, width: number, height: number, exif: any, tags: Array<string | null> | null, focalPoint: { x: number, y: number } | null, location: { lat: number | null, lon: number | null } | null } | null> | null } | null };

export type PhotoSetIdsQueryQueryVariables = Exact<{ [key: string]: never; }>;


export type PhotoSetIdsQueryQuery = { photoSets: Array<{ slug: string, photos: Array<{ id: string } | null> | null } | null> };

export const SiteSettingsSharedFragmentDoc = gql`
    fragment SiteSettingsShared on SiteSettings {
  siteTitle
  metaDescription
}
    `;
export const PageHomeQueryDocument = gql`
    query PageHomeQuery {
  siteSettings {
    intro
    ...SiteSettingsShared
  }
  posts(limit: 5) {
    publishedDate
    title
    slug
  }
  books: books(limit: 3, collection: READING, source: GOODREADS) {
    title
    author
    url
    coverUrl
  }
}
    ${SiteSettingsSharedFragmentDoc}`;

/**
 * __usePageHomeQueryQuery__
 *
 * To run a query within a React component, call `usePageHomeQueryQuery` and pass it any options that fit your needs.
 * When your component renders, `usePageHomeQueryQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = usePageHomeQueryQuery({
 *   variables: {
 *   },
 * });
 */
export function usePageHomeQueryQuery(baseOptions?: Apollo.QueryHookOptions<PageHomeQueryQuery, PageHomeQueryQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<PageHomeQueryQuery, PageHomeQueryQueryVariables>(PageHomeQueryDocument, options);
      }
export function usePageHomeQueryLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<PageHomeQueryQuery, PageHomeQueryQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<PageHomeQueryQuery, PageHomeQueryQueryVariables>(PageHomeQueryDocument, options);
        }
// @ts-ignore
export function usePageHomeQuerySuspenseQuery(baseOptions?: Apollo.SuspenseQueryHookOptions<PageHomeQueryQuery, PageHomeQueryQueryVariables>): Apollo.UseSuspenseQueryResult<PageHomeQueryQuery, PageHomeQueryQueryVariables>;
export function usePageHomeQuerySuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<PageHomeQueryQuery, PageHomeQueryQueryVariables>): Apollo.UseSuspenseQueryResult<PageHomeQueryQuery | undefined, PageHomeQueryQueryVariables>;
export function usePageHomeQuerySuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<PageHomeQueryQuery, PageHomeQueryQueryVariables>) {
          const options = baseOptions === Apollo.skipToken ? baseOptions : {...defaultOptions, ...baseOptions}
          return Apollo.useSuspenseQuery<PageHomeQueryQuery, PageHomeQueryQueryVariables>(PageHomeQueryDocument, options);
        }
export type PageHomeQueryQueryHookResult = ReturnType<typeof usePageHomeQueryQuery>;
export type PageHomeQueryLazyQueryHookResult = ReturnType<typeof usePageHomeQueryLazyQuery>;
export type PageHomeQuerySuspenseQueryHookResult = ReturnType<typeof usePageHomeQuerySuspenseQuery>;
export type PageHomeQueryQueryResult = Apollo.QueryResult<PageHomeQueryQuery, PageHomeQueryQueryVariables>;
export const MusicStatusQueryDocument = gql`
    query MusicStatusQuery {
  musicStatus {
    timestamp
    isPlaying
    playlist {
      name
      coverUrl
      spotifyUrl
    }
    song {
      albumImageUrl
      artist
      title
      spotifyUrl
      album
    }
  }
}
    `;

/**
 * __useMusicStatusQueryQuery__
 *
 * To run a query within a React component, call `useMusicStatusQueryQuery` and pass it any options that fit your needs.
 * When your component renders, `useMusicStatusQueryQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useMusicStatusQueryQuery({
 *   variables: {
 *   },
 * });
 */
export function useMusicStatusQueryQuery(baseOptions?: Apollo.QueryHookOptions<MusicStatusQueryQuery, MusicStatusQueryQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<MusicStatusQueryQuery, MusicStatusQueryQueryVariables>(MusicStatusQueryDocument, options);
      }
export function useMusicStatusQueryLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<MusicStatusQueryQuery, MusicStatusQueryQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<MusicStatusQueryQuery, MusicStatusQueryQueryVariables>(MusicStatusQueryDocument, options);
        }
// @ts-ignore
export function useMusicStatusQuerySuspenseQuery(baseOptions?: Apollo.SuspenseQueryHookOptions<MusicStatusQueryQuery, MusicStatusQueryQueryVariables>): Apollo.UseSuspenseQueryResult<MusicStatusQueryQuery, MusicStatusQueryQueryVariables>;
export function useMusicStatusQuerySuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<MusicStatusQueryQuery, MusicStatusQueryQueryVariables>): Apollo.UseSuspenseQueryResult<MusicStatusQueryQuery | undefined, MusicStatusQueryQueryVariables>;
export function useMusicStatusQuerySuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<MusicStatusQueryQuery, MusicStatusQueryQueryVariables>) {
          const options = baseOptions === Apollo.skipToken ? baseOptions : {...defaultOptions, ...baseOptions}
          return Apollo.useSuspenseQuery<MusicStatusQueryQuery, MusicStatusQueryQueryVariables>(MusicStatusQueryDocument, options);
        }
export type MusicStatusQueryQueryHookResult = ReturnType<typeof useMusicStatusQueryQuery>;
export type MusicStatusQueryLazyQueryHookResult = ReturnType<typeof useMusicStatusQueryLazyQuery>;
export type MusicStatusQuerySuspenseQueryHookResult = ReturnType<typeof useMusicStatusQuerySuspenseQuery>;
export type MusicStatusQueryQueryResult = Apollo.QueryResult<MusicStatusQueryQuery, MusicStatusQueryQueryVariables>;
export const PostQueryDocument = gql`
    query PostQuery($slug: String!) {
  siteSettings {
    avatar {
      url
    }
    ...SiteSettingsShared
  }
  post(slug: $slug) {
    body
    coverUrl
    coverAlt
    metaDescription
    publishedDate
    tags
    title
  }
}
    ${SiteSettingsSharedFragmentDoc}`;

/**
 * __usePostQueryQuery__
 *
 * To run a query within a React component, call `usePostQueryQuery` and pass it any options that fit your needs.
 * When your component renders, `usePostQueryQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = usePostQueryQuery({
 *   variables: {
 *      slug: // value for 'slug'
 *   },
 * });
 */
export function usePostQueryQuery(baseOptions: Apollo.QueryHookOptions<PostQueryQuery, PostQueryQueryVariables> & ({ variables: PostQueryQueryVariables; skip?: boolean; } | { skip: boolean; }) ) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<PostQueryQuery, PostQueryQueryVariables>(PostQueryDocument, options);
      }
export function usePostQueryLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<PostQueryQuery, PostQueryQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<PostQueryQuery, PostQueryQueryVariables>(PostQueryDocument, options);
        }
// @ts-ignore
export function usePostQuerySuspenseQuery(baseOptions?: Apollo.SuspenseQueryHookOptions<PostQueryQuery, PostQueryQueryVariables>): Apollo.UseSuspenseQueryResult<PostQueryQuery, PostQueryQueryVariables>;
export function usePostQuerySuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<PostQueryQuery, PostQueryQueryVariables>): Apollo.UseSuspenseQueryResult<PostQueryQuery | undefined, PostQueryQueryVariables>;
export function usePostQuerySuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<PostQueryQuery, PostQueryQueryVariables>) {
          const options = baseOptions === Apollo.skipToken ? baseOptions : {...defaultOptions, ...baseOptions}
          return Apollo.useSuspenseQuery<PostQueryQuery, PostQueryQueryVariables>(PostQueryDocument, options);
        }
export type PostQueryQueryHookResult = ReturnType<typeof usePostQueryQuery>;
export type PostQueryLazyQueryHookResult = ReturnType<typeof usePostQueryLazyQuery>;
export type PostQuerySuspenseQueryHookResult = ReturnType<typeof usePostQuerySuspenseQuery>;
export type PostQueryQueryResult = Apollo.QueryResult<PostQueryQuery, PostQueryQueryVariables>;
export const PostsQueryDocument = gql`
    query PostsQuery {
  posts {
    publishedDate
    title
    slug
    metaDescription
  }
}
    `;

/**
 * __usePostsQueryQuery__
 *
 * To run a query within a React component, call `usePostsQueryQuery` and pass it any options that fit your needs.
 * When your component renders, `usePostsQueryQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = usePostsQueryQuery({
 *   variables: {
 *   },
 * });
 */
export function usePostsQueryQuery(baseOptions?: Apollo.QueryHookOptions<PostsQueryQuery, PostsQueryQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<PostsQueryQuery, PostsQueryQueryVariables>(PostsQueryDocument, options);
      }
export function usePostsQueryLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<PostsQueryQuery, PostsQueryQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<PostsQueryQuery, PostsQueryQueryVariables>(PostsQueryDocument, options);
        }
// @ts-ignore
export function usePostsQuerySuspenseQuery(baseOptions?: Apollo.SuspenseQueryHookOptions<PostsQueryQuery, PostsQueryQueryVariables>): Apollo.UseSuspenseQueryResult<PostsQueryQuery, PostsQueryQueryVariables>;
export function usePostsQuerySuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<PostsQueryQuery, PostsQueryQueryVariables>): Apollo.UseSuspenseQueryResult<PostsQueryQuery | undefined, PostsQueryQueryVariables>;
export function usePostsQuerySuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<PostsQueryQuery, PostsQueryQueryVariables>) {
          const options = baseOptions === Apollo.skipToken ? baseOptions : {...defaultOptions, ...baseOptions}
          return Apollo.useSuspenseQuery<PostsQueryQuery, PostsQueryQueryVariables>(PostsQueryDocument, options);
        }
export type PostsQueryQueryHookResult = ReturnType<typeof usePostsQueryQuery>;
export type PostsQueryLazyQueryHookResult = ReturnType<typeof usePostsQueryLazyQuery>;
export type PostsQuerySuspenseQueryHookResult = ReturnType<typeof usePostsQuerySuspenseQuery>;
export type PostsQueryQueryResult = Apollo.QueryResult<PostsQueryQuery, PostsQueryQueryVariables>;
export const PostsFeedQueryDocument = gql`
    query PostsFeedQuery {
  siteSettings {
    ...SiteSettingsShared
  }
  posts(limit: 5) {
    publishedDate
    title
    slug
    metaDescription
  }
}
    ${SiteSettingsSharedFragmentDoc}`;

/**
 * __usePostsFeedQueryQuery__
 *
 * To run a query within a React component, call `usePostsFeedQueryQuery` and pass it any options that fit your needs.
 * When your component renders, `usePostsFeedQueryQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = usePostsFeedQueryQuery({
 *   variables: {
 *   },
 * });
 */
export function usePostsFeedQueryQuery(baseOptions?: Apollo.QueryHookOptions<PostsFeedQueryQuery, PostsFeedQueryQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<PostsFeedQueryQuery, PostsFeedQueryQueryVariables>(PostsFeedQueryDocument, options);
      }
export function usePostsFeedQueryLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<PostsFeedQueryQuery, PostsFeedQueryQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<PostsFeedQueryQuery, PostsFeedQueryQueryVariables>(PostsFeedQueryDocument, options);
        }
// @ts-ignore
export function usePostsFeedQuerySuspenseQuery(baseOptions?: Apollo.SuspenseQueryHookOptions<PostsFeedQueryQuery, PostsFeedQueryQueryVariables>): Apollo.UseSuspenseQueryResult<PostsFeedQueryQuery, PostsFeedQueryQueryVariables>;
export function usePostsFeedQuerySuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<PostsFeedQueryQuery, PostsFeedQueryQueryVariables>): Apollo.UseSuspenseQueryResult<PostsFeedQueryQuery | undefined, PostsFeedQueryQueryVariables>;
export function usePostsFeedQuerySuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<PostsFeedQueryQuery, PostsFeedQueryQueryVariables>) {
          const options = baseOptions === Apollo.skipToken ? baseOptions : {...defaultOptions, ...baseOptions}
          return Apollo.useSuspenseQuery<PostsFeedQueryQuery, PostsFeedQueryQueryVariables>(PostsFeedQueryDocument, options);
        }
export type PostsFeedQueryQueryHookResult = ReturnType<typeof usePostsFeedQueryQuery>;
export type PostsFeedQueryLazyQueryHookResult = ReturnType<typeof usePostsFeedQueryLazyQuery>;
export type PostsFeedQuerySuspenseQueryHookResult = ReturnType<typeof usePostsFeedQuerySuspenseQuery>;
export type PostsFeedQueryQueryResult = Apollo.QueryResult<PostsFeedQueryQuery, PostsFeedQueryQueryVariables>;
export const PostsSlugsQueryDocument = gql`
    query PostsSlugsQuery {
  posts {
    slug
  }
}
    `;

/**
 * __usePostsSlugsQueryQuery__
 *
 * To run a query within a React component, call `usePostsSlugsQueryQuery` and pass it any options that fit your needs.
 * When your component renders, `usePostsSlugsQueryQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = usePostsSlugsQueryQuery({
 *   variables: {
 *   },
 * });
 */
export function usePostsSlugsQueryQuery(baseOptions?: Apollo.QueryHookOptions<PostsSlugsQueryQuery, PostsSlugsQueryQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<PostsSlugsQueryQuery, PostsSlugsQueryQueryVariables>(PostsSlugsQueryDocument, options);
      }
export function usePostsSlugsQueryLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<PostsSlugsQueryQuery, PostsSlugsQueryQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<PostsSlugsQueryQuery, PostsSlugsQueryQueryVariables>(PostsSlugsQueryDocument, options);
        }
// @ts-ignore
export function usePostsSlugsQuerySuspenseQuery(baseOptions?: Apollo.SuspenseQueryHookOptions<PostsSlugsQueryQuery, PostsSlugsQueryQueryVariables>): Apollo.UseSuspenseQueryResult<PostsSlugsQueryQuery, PostsSlugsQueryQueryVariables>;
export function usePostsSlugsQuerySuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<PostsSlugsQueryQuery, PostsSlugsQueryQueryVariables>): Apollo.UseSuspenseQueryResult<PostsSlugsQueryQuery | undefined, PostsSlugsQueryQueryVariables>;
export function usePostsSlugsQuerySuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<PostsSlugsQueryQuery, PostsSlugsQueryQueryVariables>) {
          const options = baseOptions === Apollo.skipToken ? baseOptions : {...defaultOptions, ...baseOptions}
          return Apollo.useSuspenseQuery<PostsSlugsQueryQuery, PostsSlugsQueryQueryVariables>(PostsSlugsQueryDocument, options);
        }
export type PostsSlugsQueryQueryHookResult = ReturnType<typeof usePostsSlugsQueryQuery>;
export type PostsSlugsQueryLazyQueryHookResult = ReturnType<typeof usePostsSlugsQueryLazyQuery>;
export type PostsSlugsQuerySuspenseQueryHookResult = ReturnType<typeof usePostsSlugsQuerySuspenseQuery>;
export type PostsSlugsQueryQueryResult = Apollo.QueryResult<PostsSlugsQueryQuery, PostsSlugsQueryQueryVariables>;
export const PlaylistQueryDocument = gql`
    query PlaylistQuery($id: String!) {
  spotifyPlaylist(id: $id) {
    name
    coverUrl
    trackCount
    followerCount
    spotifyUrl
  }
}
    `;

/**
 * __usePlaylistQueryQuery__
 *
 * To run a query within a React component, call `usePlaylistQueryQuery` and pass it any options that fit your needs.
 * When your component renders, `usePlaylistQueryQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = usePlaylistQueryQuery({
 *   variables: {
 *      id: // value for 'id'
 *   },
 * });
 */
export function usePlaylistQueryQuery(baseOptions: Apollo.QueryHookOptions<PlaylistQueryQuery, PlaylistQueryQueryVariables> & ({ variables: PlaylistQueryQueryVariables; skip?: boolean; } | { skip: boolean; }) ) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<PlaylistQueryQuery, PlaylistQueryQueryVariables>(PlaylistQueryDocument, options);
      }
export function usePlaylistQueryLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<PlaylistQueryQuery, PlaylistQueryQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<PlaylistQueryQuery, PlaylistQueryQueryVariables>(PlaylistQueryDocument, options);
        }
// @ts-ignore
export function usePlaylistQuerySuspenseQuery(baseOptions?: Apollo.SuspenseQueryHookOptions<PlaylistQueryQuery, PlaylistQueryQueryVariables>): Apollo.UseSuspenseQueryResult<PlaylistQueryQuery, PlaylistQueryQueryVariables>;
export function usePlaylistQuerySuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<PlaylistQueryQuery, PlaylistQueryQueryVariables>): Apollo.UseSuspenseQueryResult<PlaylistQueryQuery | undefined, PlaylistQueryQueryVariables>;
export function usePlaylistQuerySuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<PlaylistQueryQuery, PlaylistQueryQueryVariables>) {
          const options = baseOptions === Apollo.skipToken ? baseOptions : {...defaultOptions, ...baseOptions}
          return Apollo.useSuspenseQuery<PlaylistQueryQuery, PlaylistQueryQueryVariables>(PlaylistQueryDocument, options);
        }
export type PlaylistQueryQueryHookResult = ReturnType<typeof usePlaylistQueryQuery>;
export type PlaylistQueryLazyQueryHookResult = ReturnType<typeof usePlaylistQueryLazyQuery>;
export type PlaylistQuerySuspenseQueryHookResult = ReturnType<typeof usePlaylistQuerySuspenseQuery>;
export type PlaylistQueryQueryResult = Apollo.QueryResult<PlaylistQueryQuery, PlaylistQueryQueryVariables>;
export const PlacesQueryDocument = gql`
    query PlacesQuery {
  places {
    name
    locationType
    location {
      lat
      lon
    }
  }
}
    `;

/**
 * __usePlacesQueryQuery__
 *
 * To run a query within a React component, call `usePlacesQueryQuery` and pass it any options that fit your needs.
 * When your component renders, `usePlacesQueryQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = usePlacesQueryQuery({
 *   variables: {
 *   },
 * });
 */
export function usePlacesQueryQuery(baseOptions?: Apollo.QueryHookOptions<PlacesQueryQuery, PlacesQueryQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<PlacesQueryQuery, PlacesQueryQueryVariables>(PlacesQueryDocument, options);
      }
export function usePlacesQueryLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<PlacesQueryQuery, PlacesQueryQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<PlacesQueryQuery, PlacesQueryQueryVariables>(PlacesQueryDocument, options);
        }
// @ts-ignore
export function usePlacesQuerySuspenseQuery(baseOptions?: Apollo.SuspenseQueryHookOptions<PlacesQueryQuery, PlacesQueryQueryVariables>): Apollo.UseSuspenseQueryResult<PlacesQueryQuery, PlacesQueryQueryVariables>;
export function usePlacesQuerySuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<PlacesQueryQuery, PlacesQueryQueryVariables>): Apollo.UseSuspenseQueryResult<PlacesQueryQuery | undefined, PlacesQueryQueryVariables>;
export function usePlacesQuerySuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<PlacesQueryQuery, PlacesQueryQueryVariables>) {
          const options = baseOptions === Apollo.skipToken ? baseOptions : {...defaultOptions, ...baseOptions}
          return Apollo.useSuspenseQuery<PlacesQueryQuery, PlacesQueryQueryVariables>(PlacesQueryDocument, options);
        }
export type PlacesQueryQueryHookResult = ReturnType<typeof usePlacesQueryQuery>;
export type PlacesQueryLazyQueryHookResult = ReturnType<typeof usePlacesQueryLazyQuery>;
export type PlacesQuerySuspenseQueryHookResult = ReturnType<typeof usePlacesQuerySuspenseQuery>;
export type PlacesQueryQueryResult = Apollo.QueryResult<PlacesQueryQuery, PlacesQueryQueryVariables>;
export const PhotoSetsQueryDocument = gql`
    query PhotoSetsQuery($limit: Int) {
  photoSets(limit: $limit) {
    id
    title
    slug
    description
    featuredPhoto {
      description
      focalPoint {
        x
        y
      }
      url
      width
      height
    }
  }
}
    `;

/**
 * __usePhotoSetsQueryQuery__
 *
 * To run a query within a React component, call `usePhotoSetsQueryQuery` and pass it any options that fit your needs.
 * When your component renders, `usePhotoSetsQueryQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = usePhotoSetsQueryQuery({
 *   variables: {
 *      limit: // value for 'limit'
 *   },
 * });
 */
export function usePhotoSetsQueryQuery(baseOptions?: Apollo.QueryHookOptions<PhotoSetsQueryQuery, PhotoSetsQueryQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<PhotoSetsQueryQuery, PhotoSetsQueryQueryVariables>(PhotoSetsQueryDocument, options);
      }
export function usePhotoSetsQueryLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<PhotoSetsQueryQuery, PhotoSetsQueryQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<PhotoSetsQueryQuery, PhotoSetsQueryQueryVariables>(PhotoSetsQueryDocument, options);
        }
// @ts-ignore
export function usePhotoSetsQuerySuspenseQuery(baseOptions?: Apollo.SuspenseQueryHookOptions<PhotoSetsQueryQuery, PhotoSetsQueryQueryVariables>): Apollo.UseSuspenseQueryResult<PhotoSetsQueryQuery, PhotoSetsQueryQueryVariables>;
export function usePhotoSetsQuerySuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<PhotoSetsQueryQuery, PhotoSetsQueryQueryVariables>): Apollo.UseSuspenseQueryResult<PhotoSetsQueryQuery | undefined, PhotoSetsQueryQueryVariables>;
export function usePhotoSetsQuerySuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<PhotoSetsQueryQuery, PhotoSetsQueryQueryVariables>) {
          const options = baseOptions === Apollo.skipToken ? baseOptions : {...defaultOptions, ...baseOptions}
          return Apollo.useSuspenseQuery<PhotoSetsQueryQuery, PhotoSetsQueryQueryVariables>(PhotoSetsQueryDocument, options);
        }
export type PhotoSetsQueryQueryHookResult = ReturnType<typeof usePhotoSetsQueryQuery>;
export type PhotoSetsQueryLazyQueryHookResult = ReturnType<typeof usePhotoSetsQueryLazyQuery>;
export type PhotoSetsQuerySuspenseQueryHookResult = ReturnType<typeof usePhotoSetsQuerySuspenseQuery>;
export type PhotoSetsQueryQueryResult = Apollo.QueryResult<PhotoSetsQueryQuery, PhotoSetsQueryQueryVariables>;
export const PhotoSetQueryDocument = gql`
    query PhotoSetQuery($slug: String!) {
  siteSettings {
    avatar {
      url
    }
    ...SiteSettingsShared
  }
  photoSet(slug: $slug) {
    id
    title
    slug
    description
    updatedAt
    photos {
      id
      description
      publishedAt
      focalPoint {
        x
        y
      }
      url
      width
      height
      exif
      tags
      location {
        lat
        lon
      }
    }
  }
}
    ${SiteSettingsSharedFragmentDoc}`;

/**
 * __usePhotoSetQueryQuery__
 *
 * To run a query within a React component, call `usePhotoSetQueryQuery` and pass it any options that fit your needs.
 * When your component renders, `usePhotoSetQueryQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = usePhotoSetQueryQuery({
 *   variables: {
 *      slug: // value for 'slug'
 *   },
 * });
 */
export function usePhotoSetQueryQuery(baseOptions: Apollo.QueryHookOptions<PhotoSetQueryQuery, PhotoSetQueryQueryVariables> & ({ variables: PhotoSetQueryQueryVariables; skip?: boolean; } | { skip: boolean; }) ) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<PhotoSetQueryQuery, PhotoSetQueryQueryVariables>(PhotoSetQueryDocument, options);
      }
export function usePhotoSetQueryLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<PhotoSetQueryQuery, PhotoSetQueryQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<PhotoSetQueryQuery, PhotoSetQueryQueryVariables>(PhotoSetQueryDocument, options);
        }
// @ts-ignore
export function usePhotoSetQuerySuspenseQuery(baseOptions?: Apollo.SuspenseQueryHookOptions<PhotoSetQueryQuery, PhotoSetQueryQueryVariables>): Apollo.UseSuspenseQueryResult<PhotoSetQueryQuery, PhotoSetQueryQueryVariables>;
export function usePhotoSetQuerySuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<PhotoSetQueryQuery, PhotoSetQueryQueryVariables>): Apollo.UseSuspenseQueryResult<PhotoSetQueryQuery | undefined, PhotoSetQueryQueryVariables>;
export function usePhotoSetQuerySuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<PhotoSetQueryQuery, PhotoSetQueryQueryVariables>) {
          const options = baseOptions === Apollo.skipToken ? baseOptions : {...defaultOptions, ...baseOptions}
          return Apollo.useSuspenseQuery<PhotoSetQueryQuery, PhotoSetQueryQueryVariables>(PhotoSetQueryDocument, options);
        }
export type PhotoSetQueryQueryHookResult = ReturnType<typeof usePhotoSetQueryQuery>;
export type PhotoSetQueryLazyQueryHookResult = ReturnType<typeof usePhotoSetQueryLazyQuery>;
export type PhotoSetQuerySuspenseQueryHookResult = ReturnType<typeof usePhotoSetQuerySuspenseQuery>;
export type PhotoSetQueryQueryResult = Apollo.QueryResult<PhotoSetQueryQuery, PhotoSetQueryQueryVariables>;
export const PhotoSetIdsQueryDocument = gql`
    query PhotoSetIdsQuery {
  photoSets {
    slug
    photos {
      id
    }
  }
}
    `;

/**
 * __usePhotoSetIdsQueryQuery__
 *
 * To run a query within a React component, call `usePhotoSetIdsQueryQuery` and pass it any options that fit your needs.
 * When your component renders, `usePhotoSetIdsQueryQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = usePhotoSetIdsQueryQuery({
 *   variables: {
 *   },
 * });
 */
export function usePhotoSetIdsQueryQuery(baseOptions?: Apollo.QueryHookOptions<PhotoSetIdsQueryQuery, PhotoSetIdsQueryQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<PhotoSetIdsQueryQuery, PhotoSetIdsQueryQueryVariables>(PhotoSetIdsQueryDocument, options);
      }
export function usePhotoSetIdsQueryLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<PhotoSetIdsQueryQuery, PhotoSetIdsQueryQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<PhotoSetIdsQueryQuery, PhotoSetIdsQueryQueryVariables>(PhotoSetIdsQueryDocument, options);
        }
// @ts-ignore
export function usePhotoSetIdsQuerySuspenseQuery(baseOptions?: Apollo.SuspenseQueryHookOptions<PhotoSetIdsQueryQuery, PhotoSetIdsQueryQueryVariables>): Apollo.UseSuspenseQueryResult<PhotoSetIdsQueryQuery, PhotoSetIdsQueryQueryVariables>;
export function usePhotoSetIdsQuerySuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<PhotoSetIdsQueryQuery, PhotoSetIdsQueryQueryVariables>): Apollo.UseSuspenseQueryResult<PhotoSetIdsQueryQuery | undefined, PhotoSetIdsQueryQueryVariables>;
export function usePhotoSetIdsQuerySuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<PhotoSetIdsQueryQuery, PhotoSetIdsQueryQueryVariables>) {
          const options = baseOptions === Apollo.skipToken ? baseOptions : {...defaultOptions, ...baseOptions}
          return Apollo.useSuspenseQuery<PhotoSetIdsQueryQuery, PhotoSetIdsQueryQueryVariables>(PhotoSetIdsQueryDocument, options);
        }
export type PhotoSetIdsQueryQueryHookResult = ReturnType<typeof usePhotoSetIdsQueryQuery>;
export type PhotoSetIdsQueryLazyQueryHookResult = ReturnType<typeof usePhotoSetIdsQueryLazyQuery>;
export type PhotoSetIdsQuerySuspenseQueryHookResult = ReturnType<typeof usePhotoSetIdsQuerySuspenseQuery>;
export type PhotoSetIdsQueryQueryResult = Apollo.QueryResult<PhotoSetIdsQueryQuery, PhotoSetIdsQueryQueryVariables>;